version: "3"

services:
    db:
        image: mysql:5.7
        volumes:
            - ./db_data:/var/lib/mysql
            - ./localhost.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: main_db
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        image: wordpress:latest
        depends_on:
            - db
        ports:
            - "8000:80"
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_NAME: main_db
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_TABLE_PREFIX: wp_
        volumes:
            - ./themes:/var/www/html/wp-content/themes
            - ./plugins:/var/www/html/wp-content/plugins
            - ./languages:/var/www/html/wp-content/languages

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db:3306
            - PMA_USER=wordpress
            - PMA_PASSWORD=wordpress
        depends_on:
            - db
        ports:
            - 8080:80
        volumes:
            - /sessions

    bs-wordpress:
        image: ustwo/browser-sync
        command: start --proxy "wordpress:80" --files "themes/**/*.php,themes/**/*.css"
        volumes:
            - ./themes:/source/themes
        depends_on:
            - wordpress
        ports:
            - "3000:3000"
            - "3001:3001"
